services:
  - type: web
    runtime: docker
    name: corn-project
    region: oregon
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: corn-db
          property: connectionString

databases:
  - name: corn-db
    region: oregon
    plan: free
